name: Pre-commit checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            .venv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml', '**/pdm.lock', '**/uv.lock') }}

      - name: Install UV and Python
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          python-version: "3.11"

      - run: uv venv
      - run: uv sync --dev

      - uses: tox-dev/action-pre-commit-uv@v1
        with:
          extra_args: --all-files
